"""birth date column for user

Revision ID: 8b440963ee37
Revises: ba3b30edd271
Create Date: 2025-09-29 13:04:14.734241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b440963ee37'
down_revision: Union[str, Sequence[str], None] = 'ba3b30edd271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
