"""remove extra fields

Revision ID: f07f6b1f8d0e
Revises: a16669ef2360
Create Date: 2025-10-02 13:42:35.670138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07f6b1f8d0e'
down_revision: Union[str, Sequence[str], None] = 'a16669ef2360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('country', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
